pipeline:
  print:
    image: docker
    commands:
      - echo "madnificent"
      - echo $DOCKER_USERNAME
      - echo $DOCKER_PASSWORD
    secrets: [ docker_username, docker_password ]
  build-and-push:
    image: plugins/docker
    settings:
      repo: "${CI_REPO_OWNER}/${CI_REPO_NAME%%-service}"
      tags: latest
    secrets: [ docker_username, docker_password ]
    when:
      event: push
      branch: [master, main]

